#!/usr/bin/env ts-node
/**
 * Sprint 101 – Upload and link (only PRE-EXISTING feature files)
 *
 * For Sprint 101, some work items had feature files already in the repo; others had
 * feature files generated (e.g. by the RBT generator). Test cases from the newly
 * generated feature files were already uploaded. This script uploads test cases
 * only from feature files that were already in the repo (not created/modified today).
 *
 * 1. Loads Sprint 101 work items from data/excel/Jira Sprint 101.xlsx (sheet "Jira")
 * 2. Keeps only items that have at least one feature file (UI or API) whose
 *    last-modified time is BEFORE today (i.e. pre-existing, not generated today)
 * 3. Runs Zephyr UploadAndLink for that list (upload + link to Jira).
 *
 * Usage:
 *   npx ts-node scripts/sprint-101-upload-and-link.ts
 *   npx ts-node scripts/sprint-101-upload-and-link.ts --list-only   # only list work items, no upload
 *   npm run zephyr:UploadAndLink:Sprint101
 *
 * Requires: data/excel/Jira Sprint 101.xlsx, .env.qa (or ENV) for Jira/Zephyr.
 */

import * as fs from 'fs';
import * as path from 'path';
import { spawn } from 'child_process';
import ExcelJS from 'exceljs';

const EXCEL_PATH = path.join(process.cwd(), 'data', 'excel', 'Jira Sprint 101.xlsx');
const OUTPUT_FILE = path.join(process.cwd(), 'inputs', 'sprint-101-upload-and-link.txt');

/** Start of today (midnight) in local time, as a Date (ms). */
function startOfTodayMs(): number {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
}

/**
 * True if this work item has at least one feature file that was already in the repo
 * (last modified before today). Excludes feature files created/modified today.
 */
function hasPreExistingFeatureFile(workItem: string, beforeMs: number): boolean {
  const base = process.cwd();
  const uiPath = path.join(base, 'src', 'features', 'ui', 'SF', `${workItem}.feature`);
  const apiPath = path.join(base, 'src', 'features', 'api', 'SF', `${workItem}.feature`);
  const check = (p: string) => {
    try {
      if (!fs.existsSync(p)) return false;
      const stat = fs.statSync(p);
      return stat.mtimeMs < beforeMs;
    } catch {
      return false;
    }
  };
  return check(uiPath) || check(apiPath);
}

async function loadSprint101WorkItems(): Promise<string[]> {
  if (!fs.existsSync(EXCEL_PATH)) {
    throw new Error(`Excel not found: ${EXCEL_PATH}`);
  }
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(EXCEL_PATH);
  const sheet = workbook.getWorksheet('Jira') || workbook.worksheets[0];
  if (!sheet) throw new Error('No sheet "Jira" found');

  const keys: string[] = [];
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber === 1) return;
    const cells: unknown[] = [];
    row.eachCell({ includeEmpty: true }, (c) => cells.push(c.value));
    const key = String(cells[1] || '').trim();
    if (key && /^[A-Z]+-\d+$/.test(key)) {
      keys.push(key);
    }
  });
  return keys;
}

async function main(): Promise<void> {
  const listOnly = process.argv.includes('--list-only');
  const beforeMs = startOfTodayMs();
  const todayStr = new Date().toISOString().slice(0, 10);
  console.log('Loading Sprint 101 work items from', EXCEL_PATH, '...');
  const allItems = await loadSprint101WorkItems();
  console.log(`Found ${allItems.length} work items in Sprint 101.`);
  console.log(`Considering only feature files last modified before today (${todayStr}).`);

  const preExisting = allItems.filter((key) => hasPreExistingFeatureFile(key, beforeMs));
  console.log(`${preExisting.length} work item(s) have pre-existing feature file(s) (not generated today).`);

  if (preExisting.length === 0) {
    console.log('Nothing to upload.');
    process.exit(0);
  }

  if (listOnly) {
    console.log('\nWork items to upload (pre-existing feature files):');
    preExisting.forEach((k) => console.log(k));
    process.exit(0);
  }

  const dir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  const content = [
    '# Sprint 101 – work items with PRE-EXISTING feature files (upload and link)',
    '# Only files not modified today (already in repo before Sprint 101 generation)',
    '# Generated by scripts/sprint-101-upload-and-link.ts',
    '',
    ...preExisting,
  ].join('\n');
  fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
  console.log('Wrote list to', OUTPUT_FILE);
  console.log('\nWork items:', preExisting.join(', '));
  console.log('\nRunning Zephyr UploadAndLink for these items ...\n');

  const child = spawn(
    'npx',
    ['ts-node', 'src/integrations/zephyr/upload-and-link.ts', '--file', OUTPUT_FILE],
    {
      cwd: process.cwd(),
      stdio: 'inherit',
      shell: true,
    }
  );

  child.on('close', (code) => {
    process.exit(code ?? 0);
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
